{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName}}
  namespace: {{ .Values.namespace }}
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    harness.io/skip-versioning: "true"
data:
  application.properties: |-
{{.Values.env.config | toYaml | indent 4}}
---
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.name }}
        harnessWorkflowReleaseNo: {{ randAlphaNum 10 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      serviceAccountName: {{ include "ngpp-store-cluster-aks-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:        
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.secrets .Values.env.config}}
          envFrom:
          {{- if .Values.secrets }}
          - secretRef:
              name: {{ .Values.name }}-env-secrets
          {{- end }}
          {{- if .Values.env.config }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.endpoint }}
              port: {{ .Values.deployment.httpPort }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.endpoint }}
              port: {{ .Values.deployment.httpPort }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
          env:
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: !!str {{ $value }}
            {{- end }}
            - name: vcap.application.instance_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: vcap.services.ngppci-encryptionkey.credentials.encryptedKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-env-secrets
                  key: credentials.encryptionkey
        
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.env.config }}
      volumes:
       - name: config-volume
         configMap:
           name: {{ .Values.configMapName}}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
