apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  labels:
    {{- include "ngpp-store-cluster-aks-helm.labels" . | nindent 4 }}
  {{- if .Values.artifactory.skipVersioning}}
  annotations:
    harness.io/skip-versioning: "true"
  {{- end}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "ngpp-store-cluster-aks-helm.imagePullSecretTemplate" . }}
